job: "test"
dim_size_reduction: [1,1,1]
target_mode: "target"
gpu: True
model_name: "test"
arch: "UNet3D"
AMP: True

# If training:
train_path: "data/cells/0.25z 0.125x 0.125y/train/"
valid_path: "data/cells/0.25z 0.125x 0.125y/valid/"
loss_function: "dice"
n_epochs: 3

# If testing:
test_path: "data/cells/0.25z 0.125x 0.125y/test/"
